<?
$aMenuLinks = Array(
    Array(
        "Магазин",
        "/catalog/",
        Array(),
        Array("class"=>"hide-in-header"),
        ""
    ),
    Array(
        "Сервисное обслуживание",
        "/region/",
        Array(),
        Array("class"=>"hide-in-header"),
        ""
    ),
    Array(
        "Приемные пункты",
        "/priemnie-punkti/",
        Array(),
        Array("class"=>"hide-in-header"),
        ""
    ),
    Array(
        "Оплата и доставка",
        "/buy/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Партнерам",
        "/partneram/",
        Array(),
        Array("class"=>"hide-in-footer"),
        ""
    ),
    Array(
        "Новости",
        "/news/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Отзывы",
        "/otzivi/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Полезное",
        "/articles/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Видео",
        "/videos/",
        Array(),
        Array(),
        ""
    ),
);
?>