roles:
  all:
    sentry:
      enabled: true
  dev:
    local: true
    app_env: dev
    hosts: [local]
    sentry:
      enabled: false
  stage:
    app_env: stage
    hosts: [imarket]
    sentry:
      enabled: false
  stage-tw:
    app_env: prod
    hosts: [tw]
