<?require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
require_once $_SERVER["DOCUMENT_ROOT"].'/bitrix/templates/main_page/include/phpexcel/PHPExcel/IOFactory.php';
$ID = $_REQUEST["id"];
$order = CSaleOrder::GetByID($ID);
if(!$order || $order["PAY_SYSTEM_ID"] != "5") die();
$date = ParseDateTime($order["DATE_INSERT"], "YYYY-MM-DD MI:SS");
$orderDate = $date["DD"].".".$date["MM"].".".$date["YYYY"];
$price = $order["PRICE"];
$nameProp = CSaleOrderPropsValue::GetList(Array(), Array("ORDER_ID"=>$ID, "CODE"=>"IMYA"))->GetNext();
$lastnameProp = CSaleOrderPropsValue::GetList(Array(), Array("ORDER_ID"=>$ID, "CODE"=>"FAM"))->GetNext();
$secondnameProp = CSaleOrderPropsValue::GetList(Array(), Array("ORDER_ID"=>$ID, "CODE"=>"OTCHESTVO"))->GetNext();
$addressProp = CSaleOrderPropsValue::GetList(Array(), Array("ORDER_ID"=>$ID, "CODE"=>"ADDRESS"))->GetNext();
$fio = $lastnameProp["VALUE"] . " " . $nameProp["VALUE"] . " " . $secondnameProp["VALUE"];
$address = $addressProp["VALUE"];
$book = PHPExcel_IOFactory::load("pd4.xls");
$book->getActiveSheet()->setCellValue('E11', "Оплата заказа №".$ID." от ".$orderDate);
$book->getActiveSheet()->setCellValue('E31', "Оплата заказа №".$ID." от ".$orderDate);
$book->getActiveSheet()->setCellValue('L15', $price);
$book->getActiveSheet()->setCellValue('L35', $price);
$book->getActiveSheet()->setCellValue('N13', $fio);
$book->getActiveSheet()->setCellValue('N33', $fio);
$book->getActiveSheet()->setCellValue('N14', $address);
$book->getActiveSheet()->setCellValue('N34', $address);
$objWriter = PHPExcel_IOFactory::createWriter($book, 'Excel5');
$objWriter->save("pd4_".$ID.".xls");
file_force_download($_SERVER["DOCUMENT_ROOT"]."/personal/order/kvit/pd4_".$ID.".xls");